declare module '*.jpg'
declare module '*.gif'
declare module '*.webp'
declare module '*.jpeg'
declare module '*.png'
declare module '*.svg'

declare module '*.woff2'
declare module '*.ttf'
declare module '*.eot'
declare module '*.otf'